### SSH Connections
alias archx="ssh -Y -p 27222 -l alex al.ktz.me"
alias blog="ssh -l root blog.ktz.me"

### File path shortcuts (lazy)
alias prox="cd /Users/AlexWork/Proxama/repos"
alias sok="cd /Users/Alex/Proxama/cardgateway-sok/"

### Show / hide hidden files
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

### Git shortcuts
alias gs='git status '
alias gb='git branch '
alias go='git checkout '
alias ga='git add'
alias gl='git log -10 --oneline && echo'

alias glog='git lg'

### Python crapola
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Proxama/repos
source /usr/local/bin/virtualenvwrapper.sh


